---
- name: Install apt dependencies prior to building.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libgconf2-dev
    - libgtk2.0-dev
    - libnss3-dev
    # Required for electron-builder:
    # https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux
    - icnsutils
    - graphicsmagick
    - xz-utils

# PNG icons are only relevant for Linux builds. The app ships with ICNS-format
# image files, which we'll extract into a subdirectory referred to in the
# package.json build settings.
- name: Create parent directory for PNG icons.
  file:
    path: /vagrant/build/icons
    state: directory

- name: Generate PNG-format icons.
  command: >
    icns2png --extract
    --output /vagrant/build/icons/
    /vagrant/build/icon.icns
  register: icns2png_conversion_result
  # Maddeningly the `icns2png` program fails silently if it cannot create
  # the output files! So we have to add manual error handling by inspecting
  # stderr. Also failing if exit code is non-zero, in case that ever matters.
  failed_when: icns2png_conversion_result.rc != 0 or
               'Unable to open' in icns2png_conversion_result.stderr
  args:
    # Use `make clean` in the project root to clear out old icons.
    creates: /vagrant/build/icons/app_32x32x32.png

- name: Install NodeJS dependencies via npm.
  npm:
    path: /vagrant

- name: Rebuild NodeJS dependencies
  command: npm rebuild
  args:
    chdir: /vagrant

- name: Build Sunder deb package.
  command: npm run dist
  environment: "{{ sunder_nodejs_environment_map }}"
  args:
    chdir: /vagrant
