---
- name: Install apt dependencies prior to building.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libgconf2-dev
    - libgtk2.0-dev
    - libnss3-dev
    # Required for electron-builder:
    # https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux
    - icnsutils
    - graphicsmagick
    - xz-utils

- name: Generate PNG-format icons.
  command: >
    icns2png --extract
    --output /vagrant/build/icons/
    /vagrant/build/icons/app.icns
  args:
    # Use `make clean` in the project root to clear out old icons.
    creates: /vagrant/build/icons/app_32x32x32.png

- name: Install NodeJS dependencies via npm.
  npm:
    path: /vagrant

- name: Compile CSS and JS application code.
  command: npm run build-app
  environment: "{{ sunder_nodejs_environment_map }}"
  args:
    chdir: /vagrant

- name: Build Sunder deb package.
  command: npm run dist
  environment: "{{ sunder_nodejs_environment_map }}"
  args:
    chdir: /vagrant
