---
# These packages must be installed globally, because they're referenced
# as system-wide scripts in the build process. The geerlingguy.nodejs role
# offers to handle global npm package installation, but is broken due to
# a bug in the Ansible npm module:
# https://github.com/ansible/ansible-modules-extras/issues/1375#issuecomment-186510972
- name: Install global NodeJS dependencies via npm.
  npm:
    state: present
    global: yes
    name: "{{ item }}"
  environment:
    NPM_CONFIG_PREFIX: "/usr/local/lib/npm"
    NODE_PATH: "/usr/local/lib/npm/lib/node_modules"
  with_items:
    - cross-env
    - webpack

- name: Install NodeJS dependencies via npm.
  npm:
    path: /vagrant
